import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MyContextProvider from "@/lib/MyContextProvider";
import ReduxStoreProvider from "@/redux/ReduxStoreProvider";
import { Toaster } from "sonner";
import ClientI18nProvider from "@/lib/ClientI18nProvider";
import { headers } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout is a server component so we can detect locale on the server
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Detect preferred locale via Accept-Language header (server-side)
  const hdrs: any = await headers();
  const acceptLang = (hdrs && hdrs.get && hdrs.get("accept-language")) || "";
  const locale = acceptLang.toLowerCase().startsWith("fr") ? "fr" : "en";

  // Load messages for the detected locale. Using dynamic import keeps messages
  // colocated in JSON files and lets the bundler optimize them.
  let messages: Record<string, string> = {};
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    messages = (await import(`@/locales/${locale}/common.json`)).default;
  } catch (e) {
    // fallback to english
    messages = (await import(`@/locales/en/common.json`)).default;
  }

  return (
    <html lang={locale}>
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientI18nProvider locale={locale} messages={messages}>
          <MyContextProvider>
            <ReduxStoreProvider>
              <Toaster />
              {children}
            </ReduxStoreProvider>
          </MyContextProvider>
        </ClientI18nProvider>
      </body>
    </html>
  );
}
